name: hotelbackend
services:
  minio:
    image: minio/minio:latest
    container_name: hotel-minio
    ports:
      - "9000:9000"   # Puerto API (S3)
      - "9001:9001"   # Puerto Consola Web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    # Este comando inicia el servidor y la consola
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

