# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: hotelbackend
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
  minio:
    extends:
      file: ./minio.yml
      service: minio
  mailpit:
    extends:
      file: ./mailpit.yml
      service: mailpit
volumes:
  minio_data:
